CREATE TABLE `USER_INFO`  (
  `USER_ID` bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户编号',
  `USERNAME` varchar(126) NOT NULL COMMENT '用户名',
  `PASSWORD` varchar(126) NOT NULL COMMENT '密码',
  `AGE` tinyint(3) UNSIGNED NULL DEFAULT NULL COMMENT '年龄',
  `STATUS` tinyint(3) UNSIGNED NOT NULL COMMENT '用户状态，1：正常；0：禁用',
  `CREATED_USER_ID` bigint UNSIGNED DEFAULT 0 COMMENT '创建用户编号',
  `CREATED_DATE` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_UPDATE_USER_ID` bigint UNSIGNED DEFAULT 0 COMMENT '最后更新用户编号',
  `LAST_UPDATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  PRIMARY KEY (`USER_ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 10000;


CREATE TABLE `USER_ROLE`  (
  `ROLE_ID` bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '角色编号',
  `ROLE_CODE` varchar(126) NOT NULL COMMENT '角色编码',
  `ROLE_NAME` varchar(126) NOT NULL COMMENT '角色名称',
  `STATUS` tinyint(3) UNSIGNED NOT NULL COMMENT '角色状态，1：正常；0：禁用',
  `CREATED_USER_ID` bigint UNSIGNED DEFAULT 0 COMMENT '创建用户编号',
  `CREATED_DATE` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_UPDATE_USER_ID` bigint UNSIGNED DEFAULT 0 COMMENT '最后更新用户编号',
  `LAST_UPDATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  PRIMARY KEY (`ROLE_ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 10000;


CREATE TABLE `USER_ROLE_RELATION`  (
    `RELATION_ID` bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '角色编号',
    `USER_ID` varchar(126) NOT NULL COMMENT '角色编码',
    `ROLE_ID` varchar(126) NOT NULL COMMENT '角色名称',
    `STATUS` tinyint(3) UNSIGNED NULL DEFAULT NULL COMMENT '关联关系状态，1：正常；0：禁用',
    `CREATED_USER_ID` bigint UNSIGNED DEFAULT 0 COMMENT '创建用户编号',
    `CREATED_DATE` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `LAST_UPDATE_USER_ID` bigint UNSIGNED DEFAULT 0 COMMENT '最后更新用户编号',
    `LAST_UPDATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    PRIMARY KEY (`RELATION_ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 10000;